USE ANALISIS_DATOS;
GO

/*
===============================================================================
PROJECT: Enterprise Data Warehouse (dwh-ciosa)
LAYER: Bronze (Raw Data Staging)
AUTHOR: Román Alejandro López
DESCRIPTION: DDL creation for the general customer master table using 
             the exact nvarchar and decimal structural metadata from SAP.
===============================================================================
*/


  
-- ============================================================================
-- 1. TABLE: bronze.sap_kna1 (Customer - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_kna1', 'U') IS NOT NULL 
    DROP TABLE bronze.sap_kna1;
GO

CREATE TABLE bronze.sap_kna1 (
    MANDT               NVARCHAR(3) NOT NULL,
    KUNNR               NVARCHAR(10) NOT NULL,
    LAND1               NVARCHAR(3),
    NAME1               NVARCHAR(35),
    NAME2               NVARCHAR(35),
    ORT01               NVARCHAR(35),
    PSTLZ               NVARCHAR(10),
    REGIO               NVARCHAR(3),
    SORTL               NVARCHAR(10),
    STRAS               NVARCHAR(35),
    TELF1               NVARCHAR(16),
    TELFX               NVARCHAR(31),
    XCPDK               NVARCHAR(1),
    ADRNR               NVARCHAR(10),
    MCOD1               NVARCHAR(25),
    MCOD2               NVARCHAR(25),
    MCOD3               NVARCHAR(25),
    ANRED               NVARCHAR(15),
    AUFSD               NVARCHAR(2),
    BAHNE               NVARCHAR(25),
    BAHNS               NVARCHAR(25),
    BBBNR               NVARCHAR(7),
    BBSNR               NVARCHAR(5),
    BEGRU               NVARCHAR(4),
    BRSCH               NVARCHAR(4),
    BUBKZ               NVARCHAR(1),
    DATLT               NVARCHAR(14),
    ERDAT               NVARCHAR(8),
    ERNAM               NVARCHAR(12),
    EXABL               NVARCHAR(1),
    FAKSD               NVARCHAR(2),
    FISKN               NVARCHAR(10),
    KNAZK               NVARCHAR(2),
    KNRZA               NVARCHAR(10),
    KONZS               NVARCHAR(10),
    KTOKD               NVARCHAR(4),
    KUKLA               NVARCHAR(2),
    LIFNR               NVARCHAR(10),
    LIFSD               NVARCHAR(2),
    LOCCO               NVARCHAR(10),
    LOEVM               NVARCHAR(1),
    NAME3               NVARCHAR(35),
    NAME4               NVARCHAR(35),
    NIELS               NVARCHAR(2),
    ORT02               NVARCHAR(35),
    PFACH               NVARCHAR(10),
    PSTL2               NVARCHAR(10),
    COUNC               NVARCHAR(3),
    CITYC               NVARCHAR(4),
    RPMKR               NVARCHAR(5),
    SPERR               NVARCHAR(1),
    SPRAS               NVARCHAR(1),
    STCD1               NVARCHAR(16),
    STCD2               NVARCHAR(11),
    STKZA               NVARCHAR(1),
    STKZU               NVARCHAR(1),
    TELBX               NVARCHAR(15),
    TELF2               NVARCHAR(16),
    TELTX               NVARCHAR(30),
    TELX1               NVARCHAR(30),
    LZONE               NVARCHAR(10),
    XZEMP               NVARCHAR(1),
    VBUND               NVARCHAR(6),
    STCEG               NVARCHAR(20),
    DEAR1               NVARCHAR(1),
    DEAR2               NVARCHAR(1),
    DEAR3               NVARCHAR(1),
    DEAR4               NVARCHAR(1),
    DEAR5               NVARCHAR(1),
    GFORM               NVARCHAR(2),
    BRAN1               NVARCHAR(10),
    BRAN2               NVARCHAR(10),
    BRAN3               NVARCHAR(10),
    BRAN4               NVARCHAR(10),
    BRAN5               NVARCHAR(10),
    EKONT               NVARCHAR(10),
    UMSAT               DECIMAL(18,2), -- Mapeado de tu lista de decimales
    UMJAH               NVARCHAR(4),
    UWAER               NVARCHAR(5),
    JMZAH               NVARCHAR(6),
    JMJAH               NVARCHAR(4),
    KATR1               NVARCHAR(2),
    KATR2               NVARCHAR(2),
    KATR3               NVARCHAR(2),
    KATR4               NVARCHAR(2),
    KATR5               NVARCHAR(2),
    KATR6               NVARCHAR(3),
    KATR7               NVARCHAR(3),
    KATR8               NVARCHAR(3),
    KATR9               NVARCHAR(3),
    KATR10              NVARCHAR(3),
    STKZN               NVARCHAR(1),
    UMSA1               DECIMAL(18,2), -- Mapeado de tu lista de decimales
    TXJCD               NVARCHAR(15),
    PERIV               NVARCHAR(2),
    ABRVW               NVARCHAR(3),
    INSPBYDEBI          NVARCHAR(1),
    INSPATDEBI          NVARCHAR(1),
    KTOCD               NVARCHAR(4),
    PFORT               NVARCHAR(35),
    WERKS               NVARCHAR(4),
    DTAMS               NVARCHAR(1),
    DTAWS               NVARCHAR(2),
    DUEFL               NVARCHAR(1),
    HZUOR               NVARCHAR(2),
    SPERZ               NVARCHAR(1),
    ETIKG               NVARCHAR(10),
    CIVVE               NVARCHAR(1),
    MILVE               NVARCHAR(1),
    KDKG1               NVARCHAR(2),
    KDKG2               NVARCHAR(2),
    KDKG3               NVARCHAR(2),
    KDKG4               NVARCHAR(2),
    KDKG5               NVARCHAR(2),
    XKNZA               NVARCHAR(1),
    FITYP               NVARCHAR(2),
    STCDT               NVARCHAR(2),
    STCD3               NVARCHAR(18),
    STCD4               NVARCHAR(18),
    STCD5               NVARCHAR(60),
    XICMS               NVARCHAR(1),
    XXIPI               NVARCHAR(1),
    XSUBT               NVARCHAR(3),
    CFOPC               NVARCHAR(2),
    TXLW1               NVARCHAR(3),
    TXLW2               NVARCHAR(3),
    CCC01               NVARCHAR(1),
    CCC02               NVARCHAR(1),
    CCC03               NVARCHAR(1),
    CCC04               NVARCHAR(1),
    CASSD               NVARCHAR(2),
    KNURL               NVARCHAR(132),
    J_1KFREPRE          NVARCHAR(10),
    J_1KFTBUS           NVARCHAR(30),
    J_1KFTIND           NVARCHAR(30),
    CONFS               NVARCHAR(1),
    UPDAT               NVARCHAR(8),
    UPTIM               NVARCHAR(6),
    NODEL               NVARCHAR(1),
    DEAR6               NVARCHAR(1),
    SUFRAMA             NVARCHAR(9),
    RG                  NVARCHAR(11),
    EXP                 NVARCHAR(3),
    UF                  NVARCHAR(2),
    RGDATE              NVARCHAR(8),
    RIC                 NVARCHAR(11),
    RNE                 NVARCHAR(10),
    RNEDATE             NVARCHAR(8),
    CNAE                NVARCHAR(7),
    LEGALNAT            NVARCHAR(4),
    CRTN                NVARCHAR(1),
    ICMSTAXPAY          NVARCHAR(2),
    INDTYP              NVARCHAR(2),
    TDT                 NVARCHAR(2),
    COMSIZE             NVARCHAR(2),
    DECREGPC            NVARCHAR(2),
    [VSO_R_PALHGT]      DECIMAL(18,3), -- Corchetes agregados por seguridad en nombres especiales
    [VSO_R_PAL_UL]      NVARCHAR(3),
    [VSO_R_PK_MAT]      NVARCHAR(1),
    [VSO_R_MATPAL]      NVARCHAR(18),
    [VSO_R_I_NO_LYR]    NVARCHAR(2),
    [VSO_R_ONE_MAT]     NVARCHAR(1),
    [VSO_R_ONE_SORT]    NVARCHAR(1),
    [VSO_R_ULD_SIDE]    NVARCHAR(1),
    [VSO_R_LOAD_PREF]   NVARCHAR(1),
    [VSO_R_DPOINT]      NVARCHAR(10),
    ALC                 NVARCHAR(8),
    PMT_OFFICE          NVARCHAR(5),
    PSOFG               NVARCHAR(10),
    PSOIS               NVARCHAR(20),
    PSON1               NVARCHAR(35),
    PSON2               NVARCHAR(35),
    PSON3               NVARCHAR(35),
    PSOVN               NVARCHAR(35),
    PSOTL               NVARCHAR(20),
    PSOHS               NVARCHAR(6),
    PSOST               NVARCHAR(28),
    PSOO1               NVARCHAR(50),
    PSOO2               NVARCHAR(50),
    PSOO3               NVARCHAR(50),
    PSOO4               NVARCHAR(50),
    PSOO5               NVARCHAR(50),
    CONSTRAINT PK_sap_kna1 PRIMARY KEY CLUSTERED (MANDT, KUNNR)
);
PRINT 'Table bronze.sap_kna1 created successfully using exact SAP lengths.';
GO
  
-- ============================================================================
-- 2. TABLE: bronze.sap_knvp (Customer Partner Functions - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_knvp', 'U') IS NOT NULL 
    DROP TABLE bronze.sap_knvp;
GO

CREATE TABLE bronze.sap_knvp (
    MANDT      NVARCHAR(3) NOT NULL,
    KUNNR      NVARCHAR(10) NOT NULL,
    VKORG      NVARCHAR(4) NOT NULL,
    VTWEG      NVARCHAR(2) NOT NULL,
    SPART      NVARCHAR(2) NOT NULL,
    PARVW      NVARCHAR(2) NOT NULL,
    PARZA      NVARCHAR(3) NOT NULL,
    KUNN2      NVARCHAR(10), -- Mapeado exactamente como KUNN2 de tu extracción
    LIFNR      NVARCHAR(10),
    PERNR      NVARCHAR(8),
    PARNR      NVARCHAR(10),
    KNREF      NVARCHAR(30),
    DEFPA      NVARCHAR(1),
    CONSTRAINT PK_sap_knvp PRIMARY KEY CLUSTERED (MANDT, KUNNR, VKORG, VTWEG, SPART, PARVW, PARZA)
);
PRINT 'Table bronze.sap_knvp created successfully using exact SAP lengths.';
GO

-- ============================================================================
-- 3. TABLE: bronze.sap_knkk (Customer Credit Control Data - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_knkk', 'U') IS NOT NULL 
    DROP TABLE bronze.sap_knkk;
GO

CREATE TABLE bronze.sap_knkk (
    MANDT      NVARCHAR(3) NOT NULL,
    KUNNR      NVARCHAR(10) NOT NULL,
    KKBER      NVARCHAR(4) NOT NULL,
    KLIMK      DECIMAL(15,2), -- Límite de crédito
    KNKLI      NVARCHAR(10),
    SAUFT      DECIMAL(15,2),
    SKFOR      DECIMAL(15,2), -- Obligaciones totales del cliente
    SSOBL      DECIMAL(15,2), -- Saldo deudor total especial
    UEDAT      NVARCHAR(8),
    XCHNG      NVARCHAR(1),
    ERNAM      NVARCHAR(12),
    ERDAT      NVARCHAR(8),
    CTLPC      NVARCHAR(3),
    DTREV      NVARCHAR(8),
    CRBLB      NVARCHAR(1),   -- Bloqueo de crédito
    SBGRP      NVARCHAR(3),   -- Grupo de responsables de crédito
    NXTRV      NVARCHAR(8),
    KRAUS      NVARCHAR(11),
    PAYDB      NVARCHAR(2),
    DBRAT      NVARCHAR(3),
    REVDB      NVARCHAR(8),
    AEDAT      NVARCHAR(8),
    AETXT      NVARCHAR(8),
    GRUPP      NVARCHAR(4),
    AENAM      NVARCHAR(12),
    SBDAT      NVARCHAR(8),
    KDGRP      NVARCHAR(8),
    CASHD      NVARCHAR(8),
    CASHA      DECIMAL(15,2),
    CASHC      NVARCHAR(5),
    DBPAY      NVARCHAR(3),
    DBRTG      NVARCHAR(5),
    DBEKR      DECIMAL(15,2),
    DBWAE      NVARCHAR(5),
    DBMON      NVARCHAR(8),
    ABSBT      DECIMAL(15,2),
    CONSTRAINT PK_sap_knkk PRIMARY KEY CLUSTERED (MANDT, KUNNR, KKBER)
);
PRINT 'Table bronze.sap_knkk created successfully using exact SAP lengths.';
GO



-- ============================================================================
-- TABLE: bronze.sap_knvv (Customer Sales Data - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_knvv', 'U') IS NOT NULL 
    DROP TABLE bronze.sap_knvv;
GO

CREATE TABLE bronze.sap_knvv (
    MANDT      NVARCHAR(3) NOT NULL,   -- Mandante
    KUNNR      NVARCHAR(10) NOT NULL,  -- Número de cliente
    VKORG      NVARCHAR(4) NOT NULL,   -- Organización de ventas
    VTWEG      NVARCHAR(2) NOT NULL,   -- Canal de distribución
    SPART      NVARCHAR(2) NOT NULL,   -- Sector / División
    ERNAM      NVARCHAR(12),           -- Nombre del responsable que creó el objeto
    ERDAT      NVARCHAR(8),            -- Fecha de creación (YYYYMMDD)
    BEGRU      NVARCHAR(4),            -- Grupo de autorización
    LOEVM      NVARCHAR(1),            -- Petición de borrado para el registro
    VERSG      NVARCHAR(1),            -- Esquema de estadística de cliente
    AUFSD      NVARCHAR(2),            -- Bloqueo de pedido para el cliente
    CALSG      NVARCHAR(1),            -- Esquema de calendario
    BOKRE      NVARCHAR(1),            -- Cliente abonable para rappel
    KURRF      NVARCHAR(1),            -- Factor del tipo de cambio
    PRFRE      NVARCHAR(1),            -- Determinación de precio
    KLABC      NVARCHAR(1),            -- Clasificación de clientes (ABC)
    WAERS      NVARCHAR(5),            -- Moneda de la cuenta
    KTGRD      NVARCHAR(2),            -- Grupo de imputación para este cliente
    ZTERM      NVARCHAR(4),            -- Clave de condiciones de pago / Plazo
    VWERK      NVARCHAR(4),            -- Centro de suministro (Planta por defecto)
    VKGRP      NVARCHAR(3),            -- Grupo de vendedores
    VKBUR      NVARCHAR(4),            -- Oficina de ventas
    INCO1      NVARCHAR(3),            -- Incoterms parte 1
    INCO2      NVARCHAR(28),           -- Incoterms parte 2
    LPRIO      NVARCHAR(2),            -- Prioridad de entrega
    VSBED      NVARCHAR(2),            -- Condiciones de expedición
    ANTLF      DECIMAL(1,0),           -- Límite de entregas parciales
    KZAZU      NVARCHAR(1),            -- Indicador de pedido conjunto
    AWAHR      NVARCHAR(3),            -- Probabilidad de pedido
    SPERZ      NVARCHAR(1),            -- Bloqueo de facturación para el cliente
    CONSTRAINT PK_sap_knvv PRIMARY KEY CLUSTERED (MANDT, KUNNR, VKORG, VTWEG, SPART)
);
PRINT 'Table bronze.sap_knvv created successfully using exact SAP lengths.';
GO


-- ============================================================================
-- 4. TABLE: bronze.sap_bsid (Open Items - Accounts Receivable - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_bsid', 'U') IS NOT NULL DROP TABLE bronze.sap_bsid;
GO

CREATE TABLE bronze.sap_bsid (
    MANDT           NVARCHAR(3) NOT NULL,
    BUKRS           NVARCHAR(4) NOT NULL,
    KUNNR           NVARCHAR(10) NOT NULL,
    UMSKS           NVARCHAR(1),
    UMSKZ           NVARCHAR(1),
    AUGDT           NVARCHAR(8),
    AUGBL           NVARCHAR(10),
    ZUONR           NVARCHAR(18),
    GJAHR           NVARCHAR(4) NOT NULL,
    BELNR           NVARCHAR(10) NOT NULL,
    BUZEI           NVARCHAR(3) NOT NULL,
    BUDAT           NVARCHAR(8),
    BLDAT           NVARCHAR(8),
    CPUDT           NVARCHAR(8),
    WAERS           NVARCHAR(5),
    XBLNR           NVARCHAR(16),
    BLART           NVARCHAR(2),
    MONAT           NVARCHAR(2),
    BSCHL           NVARCHAR(2),
    ZUMSK           NVARCHAR(1),
    SHKZG           NVARCHAR(1),
    GSBER           NVARCHAR(4),
    MWSKZ           NVARCHAR(2),
    DMBTR           DECIMAL(15,2), -- Monto en moneda local
    WRBTR           DECIMAL(15,2), -- Monto en moneda del documento
    MWSTS           DECIMAL(15,2),
    WMWST           DECIMAL(15,2),
    BDIFF           DECIMAL(15,2),
    BDIF2           DECIMAL(15,2),
    SGTXT           NVARCHAR(50),
    PROJN           NVARCHAR(16),
    AUFNR           NVARCHAR(12),
    ANLN1           NVARCHAR(12),
    ANLN2           NVARCHAR(4),
    SAKNR           NVARCHAR(10),
    HKONT           NVARCHAR(10),
    FKONT           NVARCHAR(3),
    FILKD           NVARCHAR(10),
    ZFBDT           NVARCHAR(8),   -- Fecha base para plazo de vencimiento
    ZTERM           NVARCHAR(4),   -- Condiciones de pago
    ZBD1T           DECIMAL(15,2),
    ZBD2T           DECIMAL(15,2),
    ZBD3T           DECIMAL(15,2),
    ZBD1P           DECIMAL(15,2),
    ZBD2P           DECIMAL(15,2),
    SKFBT           DECIMAL(15,2),
    SKNTO           DECIMAL(15,2),
    WSKTO           DECIMAL(15,2),
    ZLSCH           NVARCHAR(1),
    ZLSPR           NVARCHAR(1),
    ZBFIX           NVARCHAR(1),
    HBKID           NVARCHAR(5),
    BVTYP           NVARCHAR(4),
    REBZG           NVARCHAR(10),
    REBZJ           NVARCHAR(4),
    REBZZ           NVARCHAR(3),
    SAMNR           NVARCHAR(8),
    ANFBN           NVARCHAR(10),
    ANFBJ           NVARCHAR(4),
    ANFBU           NVARCHAR(4),
    ANFAE           NVARCHAR(8),
    MANSP           NVARCHAR(1),
    MSCHL           NVARCHAR(1),
    MADAT           NVARCHAR(8),
    MANST           NVARCHAR(1),
    MABER           NVARCHAR(2),
    XNETB           NVARCHAR(1),
    XANET           NVARCHAR(1),
    XCPDD           NVARCHAR(1),
    XINVE           NVARCHAR(1),
    XZAHL           NVARCHAR(1),
    MWSK1           NVARCHAR(2),
    DMBT1           DECIMAL(15,2),
    WRBT1           DECIMAL(15,2),
    MWSK2           NVARCHAR(2),
    DMBT2           DECIMAL(15,2),
    WRBT2           DECIMAL(15,2),
    MWSK3           NVARCHAR(2),
    DMBT3           DECIMAL(15,2),
    WRBT3           DECIMAL(15,2),
    BSTAT           NVARCHAR(1),
    VBUND           NVARCHAR(6),
    VBELN           NVARCHAR(10),
    REBZT           NVARCHAR(1),
    INFAE           NVARCHAR(8),
    STCEG           NVARCHAR(20),
    EGBLD           NVARCHAR(3),
    EGLLD           NVARCHAR(3),
    RSTGR           NVARCHAR(3),
    XNOZA           NVARCHAR(1),
    VERTT           NVARCHAR(1),
    VERTN           NVARCHAR(13),
    VBEWA           NVARCHAR(4),
    WVERW           NVARCHAR(1),
    PROJK           NVARCHAR(8),
    FIPOS           NVARCHAR(14),
    NPLNR           NVARCHAR(12),
    AUFPL           NVARCHAR(10),
    APLZL           NVARCHAR(8),
    XEGDR           NVARCHAR(1),
    DMBE2           DECIMAL(15,2),
    DMBE3           DECIMAL(15,2),
    DMB21           DECIMAL(15,2),
    DMB22           DECIMAL(15,2),
    DMB23           DECIMAL(15,2),
    DMB31           DECIMAL(15,2),
    DMB32           DECIMAL(15,2),
    DMB33           DECIMAL(15,2),
    BDIF3           DECIMAL(15,2),
    XRAGL           NVARCHAR(1),
    UZAWE           NVARCHAR(2),
    XSTOV           NVARCHAR(1),
    MWST2           DECIMAL(15,2),
    MWST3           DECIMAL(15,2),
    SKNT2           DECIMAL(15,2),
    SKNT3           DECIMAL(15,2),
    XREF1           NVARCHAR(12),
    XREF2           NVARCHAR(12),
    XARCH           NVARCHAR(1),
    PSWSL           NVARCHAR(5),
    PSWBT           DECIMAL(15,2),
    LZBKZ           NVARCHAR(3),
    LANDL           NVARCHAR(3),
    IMKEY           NVARCHAR(8),
    VBEL2           NVARCHAR(10),
    VPOS2           NVARCHAR(6),
    POSN2           NVARCHAR(6),
    ETEN2           NVARCHAR(4),
    FISTL           NVARCHAR(16),
    GEBER           NVARCHAR(10),
    DABRZ           NVARCHAR(8),
    XNEGP           NVARCHAR(1),
    KOSTL           NVARCHAR(10),
    RFZEI           NVARCHAR(3),
    KKBER           NVARCHAR(4),
    EMPFB           NVARCHAR(10),
    PRCTR           NVARCHAR(10),
    XREF3           NVARCHAR(20),
    QSSKZ           NVARCHAR(2),
    ZINKZ           NVARCHAR(2),
    DTWS1           NVARCHAR(2),
    DTWS2           NVARCHAR(2),
    DTWS3           NVARCHAR(2),
    DTWS4           NVARCHAR(2),
    XPYPR           NVARCHAR(1),
    KIDNO           NVARCHAR(30),
    ABSBT           DECIMAL(15,2),
    CCBTC           NVARCHAR(10),
    PYCUR           NVARCHAR(5),
    PYAMT           DECIMAL(15,2),
    BUPLA           NVARCHAR(4),
    SECCO           NVARCHAR(4),
    CESSION_KZ      NVARCHAR(2),
    PPDIFF          DECIMAL(15,2),
    PPDIF2          DECIMAL(15,2),
    PPDIF3          DECIMAL(15,2),
    KBLNR           NVARCHAR(10),
    KBLPOS          NVARCHAR(3),
    GRANT_NBR       NVARCHAR(20),
    GMVKZ           NVARCHAR(1),
    SRTYPE          NVARCHAR(2),
    LOTKZ           NVARCHAR(10),
    FKBER           NVARCHAR(16),
    INTRENO         NVARCHAR(13),
    PPRCT           NVARCHAR(10),
    BUZID           NVARCHAR(1),
    AUGGJ           NVARCHAR(4),
    HKTID           NVARCHAR(5),
    BUDGET_PD       NVARCHAR(10),
    PAYS_PROV       NVARCHAR(4),
    PAYS_TRAN       NVARCHAR(35),
    MNDID           NVARCHAR(35),
    KONTT           NVARCHAR(2),
    KONTL           NVARCHAR(50),
    UEBGDAT         NVARCHAR(8),
    VNAME           NVARCHAR(6),
    EGRUP           NVARCHAR(3),
    BTYPE           NVARCHAR(2),
    PROPMANO        NVARCHAR(13),
    CONSTRAINT PK_sap_bsid PRIMARY KEY CLUSTERED (MANDT, BUKRS, KUNNR, GJAHR, BELNR, BUZEI)
);
PRINT 'Table bronze.sap_bsid created successfully.';
GO

-- ============================================================================
-- 5. TABLE: bronze.sap_bsad (Cleared Items - Accounts Receivable - COMPLETE)
-- ============================================================================
IF OBJECT_ID('bronze.sap_bsad', 'U') IS NOT NULL DROP TABLE bronze.sap_bsad;
GO

-- Duplicamos la estructura exacta ya que SAP BSAD y BSID comparten el mismo layout técnico
CREATE TABLE bronze.sap_bsad (
    MANDT           NVARCHAR(3) NOT NULL,
    BUKRS           NVARCHAR(4) NOT NULL,
    KUNNR           NVARCHAR(10) NOT NULL,
    UMSKS           NVARCHAR(1),
    UMSKZ           NVARCHAR(1),
    AUGDT           NVARCHAR(8),
    AUGBL           NVARCHAR(10),
    ZUONR           NVARCHAR(18),
    GJAHR           NVARCHAR(4) NOT NULL,
    BELNR           NVARCHAR(10) NOT NULL,
    BUZEI           NVARCHAR(3) NOT NULL,
    BUDAT           NVARCHAR(8),
    BLDAT           NVARCHAR(8),
    CPUDT           NVARCHAR(8),
    WAERS           NVARCHAR(5),
    XBLNR           NVARCHAR(16),
    BLART           NVARCHAR(2),
    MONAT           NVARCHAR(2),
    BSCHL           NVARCHAR(2),
    ZUMSK           NVARCHAR(1),
    SHKZG           NVARCHAR(1),
    GSBER           NVARCHAR(4),
    MWSKZ           NVARCHAR(2),
    DMBTR           DECIMAL(15,2),
    WRBTR           DECIMAL(15,2),
    MWSTS           DECIMAL(15,2),
    WMWST           DECIMAL(15,2),
    BDIFF           DECIMAL(15,2),
    BDIF2           DECIMAL(15,2),
    SGTXT           NVARCHAR(50),
    PROJN           NVARCHAR(16),
    AUFNR           NVARCHAR(12),
    ANLN1           NVARCHAR(12),
    ANLN2           NVARCHAR(4),
    SAKNR           NVARCHAR(10),
    HKONT           NVARCHAR(10),
    FKONT           NVARCHAR(3),
    FILKD           NVARCHAR(10),
    ZFBDT           NVARCHAR(8),
    ZTERM           NVARCHAR(4),
    ZBD1T           DECIMAL(15,2),
    ZBD2T           DECIMAL(15,2),
    ZBD3T           DECIMAL(15,2),
    ZBD1P           DECIMAL(15,2),
    ZBD2P           DECIMAL(15,2),
    SKFBT           DECIMAL(15,2),
    SKNTO           DECIMAL(15,2),
    WSKTO           DECIMAL(15,2),
    ZLSCH           NVARCHAR(1),
    ZLSPR           NVARCHAR(1),
    ZBFIX           NVARCHAR(1),
    HBKID           NVARCHAR(5),
    BVTYP           NVARCHAR(4),
    REBZG           NVARCHAR(10),
    REBZJ           NVARCHAR(4),
    REBZZ           NVARCHAR(3),
    SAMNR           NVARCHAR(8),
    ANFBN           NVARCHAR(10),
    ANFBJ           NVARCHAR(4),
    ANFBU           NVARCHAR(4),
    ANFAE           NVARCHAR(8),
    MANSP           NVARCHAR(1),
    MSCHL           NVARCHAR(1),
    MADAT           NVARCHAR(8),
    MANST           NVARCHAR(1),
    MABER           NVARCHAR(2),
    XNETB           NVARCHAR(1),
    XANET           NVARCHAR(1),
    XCPDD           NVARCHAR(1),
    XINVE           NVARCHAR(1),
    XZAHL           NVARCHAR(1),
    MWSK1           NVARCHAR(2),
    DMBT1           DECIMAL(15,2),
    WRBT1           DECIMAL(15,2),
    MWSK2           NVARCHAR(2),
    DMBT2           DECIMAL(15,2),
    WRBT2           DECIMAL(15,2),
    MWSK3           NVARCHAR(2),
    DMBT3           DECIMAL(15,2),
    WRBT3           DECIMAL(15,2),
    BSTAT           NVARCHAR(1),
    VBUND           NVARCHAR(6),
    VBELN           NVARCHAR(10),
    REBZT           NVARCHAR(1),
    INFAE           NVARCHAR(8),
    STCEG           NVARCHAR(20),
    EGBLD           NVARCHAR(3),
    EGLLD           NVARCHAR(3),
    RSTGR           NVARCHAR(3),
    XNOZA           NVARCHAR(1),
    VERTT           NVARCHAR(1),
    VERTN           NVARCHAR(13),
    VBEWA           NVARCHAR(4),
    WVERW           NVARCHAR(1),
    PROJK           NVARCHAR(8),
    FIPOS           NVARCHAR(14),
    NPLNR           NVARCHAR(12),
    AUFPL           NVARCHAR(10),
    APLZL           NVARCHAR(8),
    XEGDR           NVARCHAR(1),
    DMBE2           DECIMAL(15,2),
    DMBE3           DECIMAL(15,2),
    DMB21           DECIMAL(15,2),
    DMB22           DECIMAL(15,2),
    DMB23           DECIMAL(15,2),
    DMB31           DECIMAL(15,2),
    DMB32           DECIMAL(15,2),
    DMB33           DECIMAL(15,2),
    BDIF3           DECIMAL(15,2),
    XRAGL           NVARCHAR(1),
    UZAWE           NVARCHAR(2),
    XSTOV           NVARCHAR(1),
    MWST2           DECIMAL(15,2),
    MWST3           DECIMAL(15,2),
    SKNT2           DECIMAL(15,2),
    SKNT3           DECIMAL(15,2),
    XREF1           NVARCHAR(12),
    XREF2           NVARCHAR(12),
    XARCH           NVARCHAR(1),
    PSWSL           NVARCHAR(5),
    PSWBT           DECIMAL(15,2),
    LZBKZ           NVARCHAR(3),
    LANDL           NVARCHAR(3),
    IMKEY           NVARCHAR(8),
    VBEL2           NVARCHAR(10),
    VPOS2           NVARCHAR(6),
    POSN2           NVARCHAR(6),
    ETEN2           NVARCHAR(4),
    FISTL           NVARCHAR(16),
    GEBER           NVARCHAR(10),
    DABRZ           NVARCHAR(8),
    XNEGP           NVARCHAR(1),
    KOSTL           NVARCHAR(10),
    RFZEI           NVARCHAR(3),
    KKBER           NVARCHAR(4),
    EMPFB           NVARCHAR(10),
    PRCTR           NVARCHAR(10),
    XREF3           NVARCHAR(20),
    QSSKZ           NVARCHAR(2),
    ZINKZ           NVARCHAR(2),
    DTWS1           NVARCHAR(2),
    DTWS2           NVARCHAR(2),
    DTWS3           NVARCHAR(2),
    DTWS4           NVARCHAR(2),
    XPYPR           NVARCHAR(1),
    KIDNO           NVARCHAR(30),
    ABSBT           DECIMAL(15,2),
    CCBTC           NVARCHAR(10),
    PYCUR           NVARCHAR(5),
    PYAMT           DECIMAL(15,2),
    BUPLA           NVARCHAR(4),
    SECCO           NVARCHAR(4),
    CESSION_KZ      NVARCHAR(2),
    PPDIFF          DECIMAL(15,2),
    PPDIF2          DECIMAL(15,2),
    PPDIF3          DECIMAL(15,2),
    KBLNR           NVARCHAR(10),
    KBLPOS          NVARCHAR(3),
    GRANT_NBR       NVARCHAR(20),
    GMVKZ           NVARCHAR(1),
    SRTYPE          NVARCHAR(2),
    LOTKZ           NVARCHAR(10),
    FKBER           NVARCHAR(16),
    INTRENO         NVARCHAR(13),
    PPRCT           NVARCHAR(10),
    BUZID           NVARCHAR(1),
    AUGGJ           NVARCHAR(4),
    HKTID           NVARCHAR(5),
    BUDGET_PD       NVARCHAR(10),
    PAYS_PROV       NVARCHAR(4),
    PAYS_TRAN       NVARCHAR(35),
    MNDID           NVARCHAR(35),
    KONTT           NVARCHAR(2),
    KONTL           NVARCHAR(50),
    UEBGDAT         NVARCHAR(8),
    VNAME           NVARCHAR(6),
    EGRUP           NVARCHAR(3),
    BTYPE           NVARCHAR(2),
    PROPMANO        NVARCHAR(13),
    CONSTRAINT PK_sap_bsad PRIMARY KEY CLUSTERED (MANDT, BUKRS, KUNNR, GJAHR, BELNR, BUZEI)
);
PRINT 'Table bronze.sap_bsad created successfully.';
GO
